### ISSUE TITLE
Filter by URL Hash

### ISSUE THREAD

**Issue by matobeag** [CodyHouse/cd-filter-changelog#1]
Hi 👋 

Is it possible to add an Hash to the URL for the current filter? My client wants to link directly to the filter categories e.g.: https://example.com/products#category-1

**Comment by claudia-romano** [comment]
Hi there,
this option is not included in the filter component at the moment but you can set an initial filter status. More info here:
https://codyhouse.co/ds/components/info/filter#initial-status

Based on your url, you can set the proper checked/selected attribute and/or classes.

Hope this helps! Cheers.

**Comment by solutiondrop** [comment]
Any chance this option will be baked into the component in the future? 

I used to filter by URL hash with Isotope and it was a great way for stores to create a link that automatically shows only the filtered products. I'll go ahead and try to figure out how to set the checked attribute with javascript from the URL, but I'd love it if this had a built in method. Thanks!

**Comment by schmolzp** [comment]
I think this would be a great feature to have built into this component as well.
